#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $D3VIL_REPO == "D3vilBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0QzS1JJU0gvRDN2aWxVc2VyYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $D3VIL_REPO == "D3vilbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0QzS1JJU0gvRDN2aWxVc2VyYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $D3VIL_REPO =~ $regex ]]
    then
        if [[ $D3VIL_REPO_BRANCH ]]
        then
            echo "${D3VIL_REPO}/archive/${D3VIL_REPO_BRANCH}.zip"
        else
            echo "${D3VIL_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0QzS1JJU0gvRDN2aWxVc2VyYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="myd3vilbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    D3VILPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $D3VILPATH
    echo "  • Starting D3vilBot •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m d3vilbot
}

start_bot
